# Generated by Django 4.2.6 on 2023-11-20 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency_app', '0003_currency_historicalexchangerate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExchangeRate',
        ),
    ]
