# Generated by Django 4.2.6 on 2024-01-04 20:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('currency_app', '0005_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usd_balance', models.DecimalField(decimal_places=2, default=1000.0, max_digits=10)),
                ('eur_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('gbp_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('jpy_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
